services:
  tmscrapper:
    image: tmscrapper
    container_name: tmscrapper
    build:
      context: ./
      # dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
